app:
    resource: '@AppBundle/Controller/'
    type: annotation

users:
    type:     rest
    prefix:   api
    resource: '@AppBundle/Controller/UsersController.php'

blogs:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/BlogsController.php'

clients:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/ClientsController.php'


api_login_check:
   path: /api/login_check
