app:
    resource: '@AppBundle/Controller/'
    type: annotation

users:
    #prefix: /api #odo : uncomment 
    type:     rest
    prefix:   api
    resource: '@AppBundle/Controller/UsersController.php'

api_login_check:
   path: /api/login_check
