app:
    resource: '@AppBundle/Controller/'
    type: annotation

users:
    type:     rest
    prefix:   api
    resource: '@AppBundle/Controller/UsersController.php'

ping:
    type:     rest
    prefix:   api
    resource: '@AppBundle/Controller/PingController.php'

bg:
  resource: '@BgBundle/Resources/config/routing/routes.yml'

api_login_check:
   path: /api/login_check
