wc:
    resource: '@WcBundle/Resources/config/routing/routes.yml'
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

users:
    type:     rest
    prefix:   api
    resource: '@AppBundle/Controller/UsersController.php'

ping:
    type:     rest
    prefix:   api
    resource: '@AppBundle/Controller/PingController.php'


api_login_check:
   path: /api/login_check
