export const NAV = {
  signup: '/auth/subscribe',
  confirmEmail: '/auth/password/email',
  resetPassword: '/auth/password/reset',
  search: '/dashboard/search',
  profile: '/dashboard/profile',
  profileSettings: '/dashboard/profile/settings',
  discussion: '/dashboard/discussion',
  currentDiscussion: '/dashboard/discussion/current',
  aboutUs: '/doc/about-us',
  peerLearning: '/doc/peer-learning',
  mentionsLegales: '/doc/mentionslegales',
  cookiePolicy: '/doc/cookie-policy',
  manifest: '/doc/manifest',
  home: '/signin',
  tagSearchBar: '/tag/searchBar',
  notFound: '/404',
};
