export const NAV = {
  signup: '/auth/subscribe',
  confirmEmail: '/auth/password/email',
  resetPassword: '/auth/password/reset',
  search: '/dashboard/search',
  dashHome: '/dashboard',
  profilePublic: '/dashboard/profile/public',
  profileSettings: '/dashboard/profile/home',
  settings: '/dashboard/profile/settings',
  discussion: '/dashboard/discussion/list',
  currentDiscussion: '/dashboard/discussion/current',
  aboutUs: '/doc/about-us',
  peerLearning: '/doc/peer-learning',
  mentionsLegales: '/doc/mentionslegales',
  cookiePolicy: '/doc/cookie-policy',
  manifest: '/doc/manifest',
  landing: '/auth/signin',
  signin: '/auth/signin',
  tagSearchBar: '/tag/searchBar',
  notFound: '/404',
  adminUsers: '/dashboard/admin/users',
  adminTags: '/dashboard/admin/tags',
  adminTagDomains: '/dashboard/admin/tag-domains',
  adminDomains: '/dashboard/admin/domains',
};
