#!/bin/bash

mkdir -p /src/app/var/jwt
openssl genrsa -out /src/app/var/jwt/private.pem -aes256 -passout pass:thisIsNotASecret_changeId!
openssl rsa -pubout -in /src/app/var/jwt/private.pem -out /src/app/var/jwt/public.pem -passin pass:thisIsNotASecret_changeId!