admin:
  type: rest
  prefix: api
  resource: App\_Admin\Controller\AdminController


chat:
  type:     rest
  prefix:   api
  resource: App\_Application\Controller\MessageController


tag:
  type:     rest
  prefix:   api
  resource: App\_Application\Controller\TagController


search:
  type:     rest
  prefix:   api
  resource: App\_Application\Controller\SearchController


user:
  type:     rest
  prefix:   api
  resource: App\_Application\Controller\UserController

newuser:
  type:     rest
  prefix:   api
  resource: App\_Application\Controller\NewUserController


profile:
  prefix: api
  type: rest
  resource: App\_Application\Controller\ProfileController


ping:
  type:     rest
  prefix:   api
  resource: App\_Application\Controller\PingController

upload:
  type:     rest
  prefix:   api
  resource: App\_Application\Controller\UploadController
