version: "3.1"
services:
  node:
    volumes:
    - ./../:/src
    tty: true
    image: node:8.15.0
    ports:
    - "44:44"
    links:
    - rabbit

  rabbit:
    image: rabbitmq:3
    hostname: brocker
    ports:
    - "5672:5672"
    environment:
    - RABBITMQ_ERLANG_COOKIE=secret
    - RABBITMQ_DEFAULT_USER=wcl
    - RABBITMQ_DEFAULT_PASS=inReusableCodeWeTrust

