version: "3.1"
services:
# api container
  api:
    build: docker/php
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./:/src
        - ./docker/php/nginxConf/:/etc/nginx/conf.d/
        - ./api/var/jwt:/src/api/var/jwt
        - ./var/log/RunProgrammation:/var/log/RunProgrammation
        - /dev/log:/dev/log
        - /etc/letsencrypt:/etc/letsencrypt
        - ./docker/php/nginxDefault/nginx.conf:/etc/nginx/nginx.conf
    environment:
        - ENV=${ENV}
    links:
        - db

# ssl is used to create jwt private tokens for user authentication
  ssl:
    build: docker/ssl
    volumes:
        - ./api/var/jwt:/src/api/var/jwt

# front container
  node:
    volumes:
       - ./front/:/src
       - /var/log/RunProgrammation:/var/log/RunProgrammation
    tty: true
    build: docker/node
    ports:
      - "8080:8080"
      - "3000:3000"

# database container for dev only
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=inReusableCodeWeTrust
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=simplon
      - MYSQL_PASSWORD=inCodeWeTrust
      - TERM=dumb
    volumes:
      - ./docker/db:/etc/mysql/conf.d
      - ./docker/:/opt
    tty: true
    logging:
      driver: syslog

# phpmyadmin for dev only
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports :
      - "85:80"
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=inReusableCodeWeTrust
    links:
      - db:db
