version: '3.7'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=inReusableCodeWeTrust
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=simplon
      - MYSQL_PASSWORD=inCodeWeTrust
      - TERM=dumb
    volumes:
      - ./db/mysql:/var/lib/mysql
  api:
    build: ./docker/php
    volumes:
      - ./api:/application
      - ./logs/symfony:/appliation/var/log:cached
      - /dev/log:/dev/log
    links:
      - db
      - mercure
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "85:80"
    links:
      - db
  webserver:
    image: nginx
    working_dir: /application
    volumes:
      - ./api:/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - api
      - mercure
  composer:
    build: docker/composer
    working_dir: /application
    volumes:
      - ./api:/application
  angular:
    build: docker/node
    volumes:
       - ./front/:/src
    command: "ng serve --host 0.0.0.0 --port 4200"
    tty: true
    ports:
      - "4200:4200"
  mercure:
    image: dunglas/mercure
    environment:
      - JWT_KEY=aVerySecretKey
      - DEMO=0
      - ALLOW_ANONYMOUS=1
      - PUBLISH_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_ORIGINS=http://localhost:4200 # space between origins
      - DEBUG=1
    ports:
      - "3000:80"
