version: "3.1"
services:
  api:
    build: docker/php
    ports:
        - "88:88"
        - "443:443"
    volumes:
        - ./:/src
        - ./docker/php/nginxConf/:/etc/nginx/conf.d/
        - ./api/var/jwt:/src/api/var/jwt
        - ./docker/var/log/RunProgrammation:/var/log/RunProgrammation
        - /dev/log:/dev/log
        - /etc/letsencrypt:/etc/letsencrypt
        - ./docker/php/nginxDefault/nginx.conf:/etc/nginx/nginx.conf
    environment:
        - ENV=${ENV}
    links:
        - db
        - rabbit

  angular:
    volumes:
       - ./front/:/src
       - /var/log/RunProgrammation:/var/log/RunProgrammation
    tty: true
    build: docker/node
    ports:
      - "8080:8080"
      - "3000:3000"

  socket:
    volumes:
      - ./node:/src
    tty: true
    image: node:8.15.0
    ports:
      - "44:44"
    links:
      - api
      - rabbit
  db:
    image: mariadb
    restart: always
    ports:
      - "3308:3308"
    environment:
      - MYSQL_ROOT_PASSWORD=inReusableCodeWeTrust
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=simplon
      - MYSQL_PASSWORD=inCodeWeTrust
      - TERM=dumb
    volumes:
      - ./docker/db:/etc/mysql/conf.d
      - ./docker/:/opt
    tty: true
    logging:
      driver: syslog

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports :
      - "85:80"
    links:
      - db:db

  rabbit:
    image: rabbitmq:3
    hostname: brocker
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret
      - RABBITMQ_DEFAULT_USER=wcl
      - RABBITMQ_DEFAULT_PASS=test

