speicher210_cloudinary:
  url: '%env(resolve:CLOUDINARY_URL)%'
  #  # The next configuration variables should be defined if they are not present in the URL
  #  # The URL will take precedence
  #  cloud_name: my-cloud
  #  access_identifier:
  #    api_key: my-key
  #    api_secret: my-secret
  options:
    secure: true
