fos_user:
  db_driver:              orm
  firewall_name:          login
  user_class:             App\Services\User\Entity\User
  use_listener:           true
  use_username_form_type: true
  model_manager_name:     null  # change it to the name of your entity/document manager if you don't want to use the default one.
  service:
    mailer:               'fos_user.mailer.noop'
  from_email:
    address:        samueleyre@wecolearn.com
    sender_name:    wecolearn
