jms_serializer:
    handlers:
        datetime:
            default_timezone: "Europe/Paris"
    metadata:
        auto_detection: false
        directories:
            FOSUserBundle:
                namespace_prefix: "FOS\\UserBundle"
                path:             "%kernel.project_dir%/src/Services/User/Serializer/fos"
            User:
                namespace_prefix: "App\\Services\\User\\Entity"
                path:             "%kernel.project_dir%/src/Services/User/Serializer"
            Tag:
                namespace_prefix: "App\\Services\\Tag\\Entity"
                path:             "%kernel.project_dir%/src/Services/Tag/Serializer"
            Domain:
                namespace_prefix: "App\\Services\\Domain\\Entity"
                path:             "%kernel.project_dir%/src/Services/Domain/Serializer"
            Message:
                namespace_prefix: "App\\Services\\Chat\\Entity"
                path:             "%kernel.project_dir%/src/Services/Chat/Serializer"
            Shared:
                namespace_prefix: "App\\Services\\Shared\\Entity"
                path:             "%kernel.project_dir%/src/Services/Shared/Serializer"
