lexik_jwt_authentication:
    secret_key: '%env(JWT_SECRET_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: '%env(JWT_TTL)%'
    encoder:
        # token encoder/decoder service - default implementation based on the lcobucci/jwt library
        service:            lexik_jwt_authentication.encoder.lcobucci
        # encryption algorithm used by the encoder service
        signature_algorithm: HS512
