security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface:        sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain :
                providers: [in_memory, fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory:
                users:

    firewalls:

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                provider: fos_userbundle
                check_path: /api/login_check
                require_previous_session: false
                username_parameter: email
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        signup:
            pattern:   ^/api/signup
            stateless: true
            anonymous: true

        confirmEmail:
            pattern:   ^/api/confirmEmail
            stateless: true
            anonymous: true

        inviteFriend:
            pattern: ^/api/inviteFriend
            stateless: true
            anonymous: true

        findTag:
            pattern:   ^/api/tag/find
            stateless: true
            anonymous: true

        getPopularDomainsAsTags:
            pattern: ^/api/tag/domains-popular-as-tags
            stateless: true
            anonymous: true

        resetPassword:
            pattern:   ^/api/resetPassword
            stateless: true
            anonymous: true

        api:
            pattern:   ^/api
            stateless: true
            provider: fos_userbundle
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer


    access_control:
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/confirmEmail, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/inviteFriend, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/resetPassword, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/tag/find, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/tag/domains-popular-as-tags, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/admin, roles: ROLES_SUPER_ADMIN }
