parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        entity_managers:
            default:
                dql:
                    numeric_functions:
                        pow: Oro\ORM\Query\AST\Functions\Numeric\Pow
                        cast: Oro\ORM\Query\AST\Functions\Cast
                        round: App\Dql\Round
                        cos: DoctrineExtensions\Query\Mysql\Cos
                #auto_generate_proxy_classes: true
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                    _User:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/_User/Infrastructure/Persistence/doctrine/mapping'
                        prefix: 'App\_User\DomainModel'
                        alias: _User
                    _Tag:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/_Tag/Infrastructure/Persistence/doctrine/mapping'
                        prefix: 'App\_Tag\DomainModel\Tag'
                        alias: _Tag
                    _Message:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/_Chat/Infrastructure/Persistence/doctrine/mapping'
                        prefix: 'App\_Chat\DomainModel\Message'
                        alias: _Message
                    _Domain:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/_Application/Infrastructure/Persistence/doctrine/mapping'
                        prefix: 'App\_Application\Domain'
                        alias: _Domain

