nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth','Content-Type', 'Authorization','X-Pagination','undefined']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE','PATCH','OPTIONS']
            allow_credentials: true
            max_age: 3600
