security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface:        sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain :
                providers: [in_memory, fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory:
                users:

    firewalls:

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            #pattern:  ^/api/(_(profiler|wdt|doc))/
            pattern:  ^/(api/(_(wdt|doc)))/
            security: false



        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            form_login:
                check_path: /api/login_check
                require_previous_session: false
                username_parameter: email
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        #        admin:
        #            pattern: ^/api/admin
        #            stateless: true
        #            anonymous: false




        newuser:
            pattern:   ^/api/newuser
            stateless: true
            anonymous: true

        confirmEmail:
            pattern:   ^/api/confirmEmail
            stateless: true
            anonymous: true

        findTag:
            pattern:   ^/api/findTag
            stateless: true
            anonymous: true

        resetPassword:
            pattern:   ^/api/resetPassword
            stateless: true
            anonymous: true

        api:
            pattern:   ^/api
            stateless: true
            provider: fos_userbundle
            #guard:
            #    authenticators:
            #    - lexik_jwt_authentication.jwt_token_authenticator
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer



    access_control:
    - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/newuser, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/confirmEmail, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/resetPassword, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/findTag, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
    - {path: ^/api/admin, roles: ROLES_ADMIN}
