#!/bin/bash

# ulimit and other shenanigans here ..
ulimit -n 102400

# Export all the RABBITMQ prefixed variables here ..
export RABBITMQ_*

# Export the chptst -u user's HOME
export HOME=/var/lib/rabbitmq
cd $HOME

# Boom!
exec chpst -u rabbitmq /usr/sbin/rabbitmq-server

