version: "3.1"
services:
  web:
    build: php
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./../.:/src
        - ./php/nginxConf/dev.conf:/etc/nginx/conf.d/site.conf
        - ./../appService/var/jwt:/src/appService/var/jwt
        - ./var/log/RunProgrammation:/var/log/RunProgrammation
        - /dev/log:/dev/log
    links:
        - db
        - rabbit
  ssl:
    build: ssl
    volumes:
        - ./../appService/var/jwt:/src/appService/var/jwt

  node:
    volumes:
       - ./../front/:/src
       - /var/log/RunProgrammation:/var/log/RunProgrammation
    tty: true
    build: node
    ports:
      - "8080:8080"


  rabbit:
    build: rabbit
    tty: true
    ports:
        - "5672:5672"
    volumes:
        - ./:/root
        - /var/log/rabbitmq_bg:/var/log/rabbimq
    logging:
      driver: syslog
      

  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=b1otope
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=ed
      - MYSQL_PASSWORD=b1otope
      - TERM=dumb
    volumes:
      - ./db:/etc/mysql/conf.d
      - ./:/opt
    tty: true
    logging:
      driver: syslog

  phpmyadmin:
    image: corbinu/docker-phpmyadmin
    restart: always
    ports :
      - "85:80"
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=b1otope
    links:
      - db:mysql
