version: "3.1"
services:
  web:
    build: php
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./../.:/src
        - ./php/nginxConf/:/etc/nginx/conf.d/
        - ./../app/var/jwt:/src/app/var/jwt
        - ./var/log/RunProgrammation:/var/log/RunProgrammation
        - /dev/log:/dev/log
        - /etc/letsencrypt:/etc/letsencrypt
        - ./php/nginxDefault/nginx.conf:/etc/nginx/nginx.conf
    environment:
        - ENV=${ENV}
    links:
        - db
        - rabbit
        - memcache
  memcache:
      build: memcache
      ports:
        - "11211:11211"
  ssl:
    build: ssl
    volumes:
        - ./../app/var/jwt:/src/app/var/jwt

  node:
    volumes:
       - ./../front/:/src
       - /var/log/RunProgrammation:/var/log/RunProgrammation
    tty: true
    build: node
    ports:
      - "8080:8080"
      - "3000:3000"


  rabbit:
    build: rabbit
    tty: true
    ports:
        - "5672:5672"
    volumes:
        - ./:/root
        - /var/log/rabbitmq_bg:/var/log/rabbimq
    logging:
      driver: syslog
      

  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=inReusableCodeWeTrust
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=simplon
      - MYSQL_PASSWORD=inCodeWeTrust
      - TERM=dumb
    volumes:
      - ./db:/etc/mysql/conf.d
      - ./:/opt
    tty: true
    logging:
      driver: syslog

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports :
      - "85:80"
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=inReusableCodeWeTrust
    links:
      - db:db

  certbot:
    build: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./../.:/src