message:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/MessageController.php'

client:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/UserController.php'

newuser:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/NewUserController.php'

confirmEmail:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/UserController.php'

findTag:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/TagController.php'

upload:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/UploadController.php'

search:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/SearchController.php'

user:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/UserController.php'

ping:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/PingController.php'

