Message:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/MessageController.php'

clients:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/ClientController.php'

newuser:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/NewUserController.php'

findTag:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/TagController.php'

