Message:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/MessageController.php'

clients:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/ClientController.php'

newuser:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/NewUserController.php'

confirmEmail:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/ClientController.php'

findTag:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/TagController.php'

upload:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/UploadController.php'

search:
    type:     rest
    prefix:   api
    resource: '@WcBundle/Controller/SearchController.php'

#resetPassword:
#    type:     rest
#    prefix:   api
#    resource: '@WcBundle/Controller/ClientController.php'