#!/bin/bash

mkdir -p /src/api/var/jwt
openssl genrsa -out var/jwt/private.pem -aes256 -passout pass:oezjfozjefozi340034808346erg
openssl rsa -pubout -in var/jwt/private.pem -out var/jwt/public.pem -passin pass:oezjfozjefozi340034808346erg