#!/bin/bash

mkdir -p /src/api/var/jwt
openssl genrsa -out /src/api/var/jwt/private.pem -aes256 -passout pass:thisIsNotASecret_changeIt!
openssl rsa -pubout -in /src/api/var/jwt/private.pem -out /src/api/var/jwt/public.pem -passin pass:thisIsNotASecret_changeIt!