blogs:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/BlogsController.php'

clients:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/ClientsController.php'

ancres:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/AncresController.php'

clefs:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/ClefsController.php'

neutres:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/NeutresController.php'