Bg\BgBundle\Entity\Blog:
    exclusion_policy: all
    access_order:     alphabetical
    properties:
        id:
          groups: [ input, output ]
        name:
          groups: [ input, output ]
        url:
          groups: [ input, output ]
        login:
          groups: [ input, output ]
        pass:
          groups: [ input, output ]
            