services:
  user.repository:
    class: WcBundle\Repository\UserRepository
  tag.repository:
    class: WcBundle\Repository\TagRepository
  message.repository:
    class: WcBundle\Repository\MessageRepository



