services:
  client.service:
    class: WcBundle\Service\ClientService
    arguments: ['@doctrine.orm.entity_manager']
  token.service:
    class: WcBundle\Service\TokenService
    arguments: ['@doctrine.orm.entity_manager']
  gppd.service:
    class: WcBundle\Service\GPPDService
    arguments: ['@doctrine.orm.entity_manager']
  email.service:
    class: WcBundle\Service\EmailService
    arguments: ['@doctrine.orm.entity_manager', 'sendinblue_api']
  message.service:
    class: WcBundle\Service\MessageService
    arguments: ['@doctrine.orm.entity_manager']
  search.service:
    class: WcBundle\Service\SearchService
    arguments: ['@doctrine.orm.entity_manager']

#commands
  client.tag.command:
    class: WcBundle\Command\ClientTag
    arguments: ['@doctrine.orm.entity_manager']
    tags:
      - { name: console.command }
