services:
  client.service:
    class: WcBundle\Service\ClientService
    arguments: ['@doctrine.orm.entity_manager' , '@domain.service', '%client_id%', '%client_secret%']
  token.service:
    class: WcBundle\Service\TokenService
    arguments: ['@doctrine.orm.entity_manager']
  gppd.service:
    class: WcBundle\Service\GPPDService
    arguments: ['@doctrine.orm.entity_manager']
  email.service:
    class: WcBundle\Service\EmailService
    arguments: ['@doctrine.orm.entity_manager', '%delivery_address%', '@sendinblue_api',  '@logger',]
    tags:
      - { name: monolog.logger}
  message.service:
    class: WcBundle\Service\MessageService
    arguments: ['@doctrine.orm.entity_manager', '%limit_until_destroy%']
  search.service:
    class: WcBundle\Service\SearchService
    arguments: ['@doctrine.orm.entity_manager']
  user.service:
    class: WcBundle\Service\UserService
    arguments: ['@doctrine.orm.entity_manager']
  domain.service:
      class: WcBundle\Service\DomainService

#commands
  client.tag.command:
    class: WcBundle\Command\ClientTag
    arguments: ['@doctrine.orm.entity_manager']
    tags:
      - { name: console.command }
  client.reminder.command:
    class: WcBundle\Command\SendReminder
    arguments: ['@doctrine.orm.entity_manager' ,'@email.service', '@message.service']
    tags:
      - { name: console.command }
