services:
  pagination.service:
      class: AppBundle\Pagination\Service

  pagination.request:
      class: AppBundle\Pagination\RequestListener
      arguments: [ '@pagination.service' ]
      tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  pagination.subscriber:
    class: AppBundle\Pagination\PaginationSubscriber
    arguments: [ '@service_container' ]
    tags:
        - { name: kernel.event_subscriber }

  AppBundle\Exception\ExceptionSubscriber:
    class: AppBundle\Exception\ExceptionSubscriber
    arguments:  ['@service_container', '@logger']
    tags:
      - { name: kernel.event_subscriber }

  pagination.response:
    class: AppBundle\Pagination\ResponseListener
    arguments: [ '@pagination.service' ]
    tags:
        - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

  command.test:
    class: AppBundle\Command\Test
    arguments : [ '@logger', '@doctrine.orm.entity_manager', '@command_bus']
    tags: 
      - { name: console.command }

  command.env:
    class: AppBundle\Command\Env
    arguments : [ '@logger' ]
    tags: 
      - { name: console.command }


  google_api_fetch_url_rank:
    class: AppBundle\GoogleSearchApi\Handler\FetchRankCommandHandler
    arguments: [ '@doctrine.orm.entity_manager' ]
    tags:
        - { name: command_handler, handles: AppBundle\GoogleSearchApi\Message\FetchRank }

  logger.std.out:
      class : AppBundle\Logger\StdOut