services:

  AppBundle\Exception\ExceptionSubscriber:
    class: AppBundle\Exception\ExceptionSubscriber
    arguments:  ['@service_container', '@logger']
    tags:
      - { name: kernel.event_subscriber }

  command.test:
    class: AppBundle\Command\Test
    arguments : [ '@logger', '@doctrine.orm.entity_manager', '@command_bus']
    tags: 
      - { name: console.command }

  command.env:
    class: AppBundle\Command\Env
    arguments : [ '@logger' ]
    tags: 
      - { name: console.command }


  google_api_fetch_url_rank:
    class: AppBundle\GoogleSearchApi\Handler\FetchRankCommandHandler
    arguments: [ '@doctrine.orm.entity_manager' ]
    tags:
        - { name: command_handler, handles: AppBundle\GoogleSearchApi\Message\FetchRank }

  logger.std.out:
      class : AppBundle\Logger\StdOut
