App\_Chat\DomainModel\Message\Message:
    exclusion_policy: all
    access_order:     alphabetical
    enable_max_depth: true
    properties:
        id:
          groups: [ input, output, message ]
        message:
          groups: [ input, output, message ]
        created:
          groups: [ output, message ]
        receiver:
          groups: [ input, output, message ]
          max_depth: 4
        sender:
          groups: [ input, output, message ]
          max_depth: 4
        isRead:
          groups: [ input, output, message ]



