#nelmio_cors:
#    defaults:
#        origin_regex: true
#        allow_credentials: true
#        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#        allow_headers: ['Accept', 'X-Custom-Auth','Content-Type', 'Authorization','X-Pagination','undefined']
#        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#        expose_headers: ['Link']
#        max_age: 3600
#    paths:
#        '^/': null
#
