hebergeurs:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/HebergeursController.php'

uploads:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/UploadsController.php'

masses:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/MassesController.php'

blogs:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/BlogsController.php'

clients:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/ClientsController.php'

ancres:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/AncresController.php'

clefs:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/ClefsController.php'

titres:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/TitresController.php'

neutres:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/NeutresController.php'

neutres-generator:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/NeutresGeneratorController.php'

evolutions:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/EvolutionsController.php'

programmations:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/ProgrammationsController.php'

recherches:
    type:     rest
    prefix:   api
    resource: '@BgBundle/Controller/RecherchesController.php'

