services:
  command.rank:
    class: Bg\BgBundle\Metier\Recherche\FetchRankCommand
    arguments : [ '@search.logger', '@command_bus', '@messenger.manager' ]
    tags: 
      - { name: console.command }
