services:
  init_handler:
    class: Bg\BgBundle\Metier\Recherche\Handler\InitCommandHandler
    tags:
        - { name: command_handler, handles: Bg\BgBundle\Metier\Recherche\Command\InitCommand }

  fetch_proxy_handler:
    class: Bg\BgBundle\Metier\Recherche\Handler\FetchProxyCommandHandler
    arguments: [ '@proxy_warehouse' ]
    tags:
        - { name: command_handler, handles: Bg\BgBundle\Metier\Recherche\Command\FetchProxyCommand }