services:
  search.log.handler:
    class: Monolog\Handler\StreamHandler
    arguments: ['/var/log/recherche.log', !php/const:Monolog\Logger::INFO ]

  search.logger:
    parent: logger.std.out
    calls:
       - ['pushHandler', [ '@search.log.handler'] ]
    

  proxy_warehouse:
    class: Bg\BgBundle\Metier\Recherche\ProxyWareHouse
    arguments: ['@doctrine.orm.entity_manager', '@search.logger']
