root:
  prefix:   /
  type: annotation
  resource: App\Services\Core\Controller\RootController

signin:
  path: /api/login_check

signup:
  type:     annotation
  prefix:   api
  resource: App\Services\User\Controller\SignUpController

ping:
  type:     annotation
  prefix:   api
  resource: App\Services\User\Controller\PingController

user:
  type:     annotation
  prefix:   api
  resource: App\Services\User\Controller\UserController

userAdmin:
  type:     annotation
  prefix:   api
  resource: App\Services\User\Controller\UserAdminController

userCommunityAdmin:
  type:     annotation
  prefix:   api
  resource: App\Services\User\Controller\UserCommunityAdminController

profile:
  prefix: api
  type: annotation
  resource: App\Services\User\Controller\ProfileController

tag:
  type:     annotation
  prefix:   api
  resource: App\Services\Tag\Controller\TagController


upload:
  type:     annotation
  prefix:   api
  resource: App\Services\User\Controller\UploadController

message:
  type:     annotation
  prefix:   api
  resource: App\Services\Chat\Controller\MessageController

adminTag:
  type:     annotation
  prefix:   api
  resource: App\Services\Tag\Controller\AdminTagController

adminTagDomain:
  type:     annotation
  prefix:   api
  resource: App\Services\Tag\Controller\AdminTagDomainController

adminDomain:
  type:     annotation
  prefix:   api
  resource: App\Services\Domain\Controller\AdminDomainController

communityAdminDomain:
  type:     annotation
  prefix:   api
  resource: App\Services\Domain\Controller\CommunityAdminDomainController
