services:
  persist_masse_handler:
    class: Bg\BgBundle\Metier\Masse\PersistMasseCommandHandler
    arguments: ['@doctrine.orm.entity_manager']
    tags:
        - { name: command_handler, handles: Bg\BgBundle\Metier\Masse\PersistMasse }
  udpate_entity:
    class: Bg\BgBundle\Metier\CommandHandler\UpdateEntityCommandHandler
    arguments: ['@doctrine.orm.entity_manager']
    tags:
        - { name: command_handler, handles: Bg\BgBundle\Metier\Command\UpdateEntity }
  fetch_entity:
    class: Bg\BgBundle\Metier\CommandHandler\FetchEntityCommandHandler
    arguments: ['@doctrine.orm.entity_manager']
    tags:
        - { name: command_handler, handles: Bg\BgBundle\Metier\Command\FetchEntity }
  fetch_random_entity:
    class: Bg\BgBundle\Metier\CommandHandler\FetchRandomEntityCommandHandler
    arguments: ['@doctrine.orm.entity_manager']
    tags:
        - { name: command_handler, handles: Bg\BgBundle\Metier\Command\FetchRandomEntity }

  launch_page_rank_recherche:
    class: Bg\BgBundle\Metier\Recherche\Handler\LaunchPageRankRechercheCommandHandler
    arguments: ['@doctrine.orm.entity_manager', '@google_api_fetch_url_rank' ]
    tags:
        - { name: command_handler, handles: Bg\BgBundle\Metier\Recherche\Command\LaunchPageRankRecherche }