services:
  masse.repository:
    class: Bg\BgBundle\Repository\MasseRepository
    arguments: [ '@doctrine.orm.entity_manager' ]

  blog.repository:
    class: Bg\BgBundle\Repository\BlogRepository
    arguments: [ '@doctrine.orm.entity_manager' ]
