services:
  blog.service:
    class: Bg\BgBundle\Service\BlogService
    arguments: ['@doctrine.orm.entity_manager']
  gppd.service:
    class: Bg\BgBundle\Service\GPPDService
    arguments: ['@doctrine.orm.entity_manager']

  subscriber.phrase_subscriber:
      class: Bg\BgBundle\Subscriber\PhraseSubscriber
      arguments: []
      tags:
          - { name: doctrine.event_subscriber }
  client.repository:
    class: Bg\BgBundle\Repository\ClientRepository
    arguments: ['@doctrine.orm.entity_manager']

  command.run_programmation:
    class: Bg\BgBundle\Command\RunProgrammation
    arguments : [ '@logger', '@doctrine.orm.entity_manager', '@command_bus']
    tags: 
      - { name: console.command }
  
