services:
    _defaults:
        public: true

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'
    test.event_dispatcher:
        public: true
        class : Tests\App\Service\TestEventDispatcher

    create_user_service:
        class: App\_User\DomainModel\User\CreateUserService
        public: true
        arguments: ['@fos_user.user_manager','@test.event_dispatcher', '@add_domain_service' , '@generate_url_service' ]

    domain_service:
        public: true
        class: App\_Application\Domain\DomainService
        arguments: ['@doctrine.orm.entity_manager', 'localhost', 'test']


    add_domain_service:
        class: \App\_Application\Domain\AddDomainService
        public: true
        arguments: ['@domain_service']


    generate_url_service:
        public: true
        class: App\_User\DomainModel\User\GenerateUrlService
        arguments: ['@doctrine.orm.entity_manager']

