WcBundle\Entity\SlackAccount:
    exclusion_policy: all
    access_order:     alphabetical
    properties:
        id:
          groups: [ input, output ]
        accountId:
          groups: [ input, output ]
        slackTeam:
          groups: [ input, output, search ]



