WcBundle\Entity\SlackTeam:
    exclusion_policy: all
    access_order:     alphabetical
    properties:
        id:
          groups: [ input, output, search ]
        teamId:
          groups: [ input, output, search ]
        name:
          groups: [ input, output ]
        type:
          groups: [ input, output, search ]



