WcBundle\Entity\Client:
    exclusion_policy: all
    access_order:     alphabetical
    enable_max_depth: true
    properties:
        id:
          groups: [ input, output ]
        created:
          groups: [ input, output ]
        firstName:
          groups: [ input, output ]
        lastName:
          groups: [ input, output ]
        profilUrl:
          groups: [ input, output ]
        biographie:
          groups: [ input, output ]
        intensity:
          groups: [ input, output ]
        atmosphere:
          groups: [ input, output ]
        latitude:
          groups: [ input, output ]
        longitude:
          groups: [ input, output ]
        tags:
          groups: [ input, output ]
        sentMessages:
          groups: [ input, output ]
          max_depth: 4
        receivedMessages:
          groups: [ input, output ]
          max_depth: 4
        user:
          groups: [ input ]
        image:
          groups: [ input, output ]
        showProfil:
          groups: [ input, output ]
        emailNotifications:
          groups: [ input, output ]



