WcBundle\Entity\Image:
    exclusion_policy: all
    access_order:     alphabetical
    properties:
        id:
          groups: [ input, output ]
        filename:
          groups: [ output, search ]
        created:
          groups: [ output ]




