WcBundle\Entity\Tag:
    exclusion_policy: all
    access_order:     alphabetical
    properties:
        id:
          groups: [ input, output ]
        name:
          groups: [ input, output ]
        type:
          groups: [ input, output ]
        created:
          groups: [ output ]
        iteration:
          groups: [ input, output ]




