import { Component, OnInit } from '@angular/core';


@Component({
  selector: 'app-auto-generated-component',
  templateUrl: './auto-generated-component.component.html',
  styleUrls: ['./auto-generated-component.component.css']
})
export class AutoGeneratedComponentComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
