FOS\UserBundle\Model\User:
    exclusion_policy: all
    access_order:     alphabetical
    properties:
        username:
          groups: [ input, output ]
        email:
          groups: [ input, output ]
        password:
          groups: [ input ]
        id:
          groups: [ output ] 
