Bg\BgBundle\Entity\Recherche:
    exclusion_policy: all
    access_order:     alphabetical
    properties:
        id:
          groups: [ input, output ]
          type: integer
        url:
          groups: [ input, output ]
          type: string
        name:
          groups: [ input, output ]
          type: string
        recherche:
          groups: [ input, output ]
          type: string
        resulats:
          groups: [ input, output ]
          type: ArrayCollection<Bg\BgBundle\Entity\Resultat>