Bg\BgBundle\Entity\Masse:
    exclusion_policy: all
    access_order:     alphabetical
    properties:
        id:
          groups: [ input, output ]
          type: integer
        name:
          groups: [ input, output ]
          type: string
        launched:
          groups: [ input, output ]
          type: integer
        programmations:
          groups: [ input, output ]
          type: ArrayCollection<Bg\BgBundle\Entity\Programmation>