Bg\BgBundle\Entity\Masse:
    exclusion_policy: all
    access_order:     alphabetical
    properties:
        name:
          groups: [ input, output ]
          type: string
        programmations:
          groups: [ input, output ]
          type: ArrayCollection<Bg\BgBundle\Entity\Programmation>