Bg\BgBundle\Entity\Resultat:
    exclusion_policy: all
    access_order:     alphabetical
    properties:
        id:
          groups: [ input, output ]
          type: integer
        rank:
          groups: [ input, output ]
          type: string
        page:
          groups: [ input, output ]
          type: string
        date:
          groups: [ input, output ]
          type: DateTime