Bg\BgBundle\Entity\Phrase:
    exclusion_policy: all
    access_order:     alphabetical
    properties:
        id:
          groups: [ input, output ]
          type: integer
        phrase:
          groups: [ input, output ]
          type: string
        idLanguage:
          serialized_name: 'idLanguage'
          type: string
          groups: [ input, output ]
        count:
          type: integer
          groups: [ output ]