Bg\BgBundle\Model\Masse:
    exclusion_policy: all
    access_order:     alphabetical
    properties:
        totalNumberProgrammation:
          groups: [ input, output ]
          type: integer
          serialized_name: totalNumberProgrammation
        neutralSentenceNumberMin:
          groups: [ input, output ]
          type: integer
          serialized_name: neutralSentenceNumberMin
        neutralSentenceNumberMax:
          groups: [ input, output ]
          type: integer
          serialized_name: neutralSentenceNumberMax
        blogs:
          groups: [ input, output ]
          type: ArrayCollection<Bg\BgBundle\Entity\Blog> 
        name:
          groups: [ input, output ]
          type: string
        isPage:
          groups: [ input, output ]
          type: integer
          serialized_name: isPage
        idLanguage:
          groups: [ input, output ]
          type: integer
          serialized_name: idLanguage
        client:
          groups: [ input, output ]
          type: Bg\BgBundle\Entity\Client
        anchorSentenceNumber:
          groups: [ input, output ]
          type: integer
          serialized_name: anchorSentenceNumber
        isBlank:
          groups: [ input, output ]
          type: integer
          serialized_name: isBlank
        pause:
          groups: [ input, output ]
          type: integer
        titleOption:
          groups: [ input, output ]
          type: integer
          serialized_name: titleOption