Bg\BgBundle\Model\Evolution:
    exclusion_policy: all
    access_order: alphabetical
    properties:
      idMasse:
        groups: [ input, output ]
        type: integer
        serialized_name: idMasse
      tics:
        groups: [ input, output ]
        type: integer
      nextProgrammation:
        groups: [ input, output ]
        type: integer
        serialized_name: nextProgrammation
      lastProgrammation:
        groups: [ input, output ]
        type: integer
        serialized_name: lastProgrammation
      last:
        groups: [ input, output ]
        type: integer
      elapsed:
        groups: [ input, output ]
        type: integer
      programmations:
        groups: [ input, output ]
        type: integer