postdeploy: php bin/console doctrine:migrations:sync-metadata-storage; php bin/console --no-interaction do:migrations:migrate; php bin/console shapecode:cron:scan; php bin/console shapecode:cron:run; php bin/console messenger:consume
clock: php cron.php
