postdeploy: php bin/console doctrine:migrations:sync-metadata-storage; php bin/console --no-interaction do:migrations:migrate; php bin/console shapecode:cron:scan; php bin/console shapecode:cron:run; php bin/console cache:clear
clock: php cron.php
worker: php bin/console messenger:consume async_priority_high async_priority_low --memory-limit=128M
