name: tests before merge

on:
  pull_request:
    branches: [ master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install scalingo CLI
        run : curl -O https://cli-dl.scalingo.com/install && bash install
      - name: Load fixtures on staging
        run : scalingo login --api-token ${{ secrets.scalingo_staging_token }}; scalingo --region osc-fr1 -a wecolearn-api-staging run "php bin/console doctrine:schema:drop --force\
          && php bin/console doctrine:schema:update --force --no-interaction\
          && php bin/console do:fi:lo -v --no-interaction"
      - name: Install cypress
        run: cd front; yarn add cypress@^4.4.1; yarn add @cypress/webpack-preprocessor@^4.1.0;
      - name: Run desktop tests on staging front
        run: cd front; CYPRESS_BASE_URL=https://staging.wecolearn.com $(npm bin)/cypress run --env ENV_NAME=staging --spec cypress/integration/e2e.ts --config video=false,chromeWebSecurity=false
      - name: Run mobile tests on staging front
        run: cd front; CYPRESS_BASE_URL=https://staging.wecolearn.com $(npm bin)/cypress run --env ENV_NAME=staging,USER_AGENT=mobile --spec cypress/integration/e2e.mobile.ts --config video=false,chromeWebSecurity=false

